### ISSUE TITLE
A.07.IR225.TGR5.ds.identification namespace should be included with identifier

### ISSUE THREAD

**Issue by pvgenuchten** [inspire-eu-validation/metadata#13]
Comment by Michael Östling:
According to IR a namespace must be included.
So we must check if a namespace and character-code is given.
ATS just mentions Identifier
FYI also the RS_Identifier will be removed from TG metadata in coming
release.

**Comment by jensscheerlinck** [comment]
Resolved by commit 01a52ee6fb99162e451e2e314a133f3248aac481
