### ISSUE TITLE
Ambiguous unique resource identifier TG requirement?

### ISSUE THREAD

**Issue by ilkkarinne** [inspire-eu-validation/metadata#131]
I just read the TG MD carefully once again, and stumbled into the fact that the ISO AP requires that the ```/*/gmd:identificationInfo/*/gmd:citation/*/``` contains an ```gmd:identifier``` with code matching the ```gmd:fileIdentifier``` of the containing metadata record (see OGC 07-045, chapter 7.2.2.1 “Extensions to ISO 19115:2003/Cor.1:2006”, last paragraph). In TG MD 2.0 (TG Requirement 1.3) we require that the this same element is used for the Unigue resource identifier of the dataset, and recommend using a resolvable, permanent identifier.

The XML Schema for CI_Citation allows more than one ```gmd:identifier``` element, so in that sense providing both would not be a problem. But if there are more than one, how does the validator know which of them is meant to be the INSPIRE Unique resource identifier of the dataset?

**Comment by cportele** [comment]
Good question, @ilkkarinne! 

In TG MD 1.3 it just requires (and tests) that an identifier is provided. There is no requirement (or test) for the fileIdentifier in TG MD 1.3 as far as I can tell and there is no CITE test for ISO AP, so the ISO AP requirement is not tested. I just note that the one example in the ISO AP spec that has MD_DataIdentification does not conform to the requirement either.

So for TG MD 1.3 and the ETS I would not change anything. For TG MD 2.0 I agree it would be good, if the requirement is clarified so that it can be tested in the ATS and ETS for v2.0.

**Comment by heidivanparys** [comment]
The aformentioned requirement from OGC 07-045 is actually repeated in the TG MD 2.0:

![image](https://user-images.githubusercontent.com/11427611/37154045-a84488e8-22d6-11e8-888a-1ba19248faeb.png)

But isn't this requirement (is it actually a requirement? or a recommendation?) the same as saying that the concept of a dataset is the same as the concept of a metadata record? Which is not the case.

I found the following in a [document regarding metadata from U.S. Geoscience Information Network](http://lab.usgin.org/sites/default/files/profile/file/u4/USGIN_ISO_Metadata_1.1.4.pdf):

![image](https://user-images.githubusercontent.com/11427611/37154294-6a6eae62-22d7-11e8-9b03-886f57ab0552.png)

So maybe the TG MD 2.0 should be updated to also reject this requirement/recommendation.

**Comment by MichaelOstling** [comment]
Does anyone know why this requirement is defined in OGC 07-045.
It just states that _To simplify catalogue mining_

**Comment by michellutz** [comment]
@aquaglia What is your view on this?

P.S. I created a new tag "version:2.0" to keep track of issues related to MD TG v2.0

**Comment by michellutz** [comment]
I just had a look at the MD TG v2.0 again and cannot find a TG requirement mandating what the ISO AP is saying.

**TG Requirement 1.3: metadata/2.0/req/datasets-and-series/dataset-uid** reads:
A unique identifier shall be given for each described dataset or data sets series. This identifier shall be a URI consisting of a namespace uniquely identifying a naming context governed by an identifier authority, and a code unique within this namespace. The identifying URI shall be encoded using gmd:citation/gmd:CI_Citation/gmd:identifier/*/gmd:code element with a Non-empty Free Text Element content. The multiplicity of this element is 1..*.

Then there are two recommendations that the ids should be persistent and resolvable. But on the ISO AP, there is just the note. 

If we believe that the ISO AP requirement is not helpful, maybe we should just remove the note in section 2.2.1 or add another comment along the lines of what the USGIN says.

But I don't see any issue with the current (or future v2.0) metadata ATS.

**Comment by PeterParslow** [comment]
@ilkkarinne : I'm curious where in the ISO AP you find that requirement. The nearest I can find, and the one that is copied as a note in INSPIRE (referenced by Heidi) isn't about "/*/gmd:identificationInfo/*/gmd:citation/*/". I took "MD_DataIdentification .... must have an identifier" to mean the thing who's XPath is MD_DataIdentification/@id. See TG Recommendation 1.1: metadata/2.0/rec/datasets-and-series/md-element-id

I'm not sure that this would work in an instance where the MD_Metadata contains more than one MD_DataIdentification. ISO AP requires all those to have the same @id, which isn't allowed under XML ID rules. But we don't allow it all for INSPIRE (TG Requirement 1.2: metadata/2.0/req/datasets-and-series/only-one-md-data-identification)

**Comment by ilkkarinne** [comment]
@PeterParslow: I could be wrong of course, but I interpreted the ISO AP sentence 

> ... each MD_DataIdentification instance being part of a MD_Metadata instance must have **an identifier having a code** value that is equal to the fileIdentifier of the owning MD_Metadata instance

to be targeting the MD_DataIdentification/gmd:identifier/*/gmd:code property.

**Comment by PeterParslow** [comment]
I have emailed the documents editors to see if they can remember what the original OGC team had in mind.

**Comment by PeterParslow** [comment]
I have this response from Uwe Voges, one of the original editors, indicating that you are correct @ilkkarinne , and I'm wrong:

"Hi,
MD_DataIdentification/gmd:identifier/*/gmd:code is correct.
Per Definition in the spec one Metadata set shall include exactly 1 Entry of  MD_DataIdentification."

So your original question stands. Sorry for my intervention!

**Comment by aquaglia** [comment]
I would like to point out that the CSW 2.0.2 specification supports
different metadata encodings: ISO 19139, ebRIM, Dublin Core, etc.

The fileIdentifier is specific to ISO 19139, so it can be declared
mandatory only in the specific profile ISO AP 1.0, which is required by the
INSPIRE MD TGs

The fileIdentifier implements the concept of metadata *record identifier*.
It identifies the metadata record in a catalogue.
It does *not necessarily identify the resource* described by the metadata
record itself.
Actually, different (maybe federated) catalogues might:
- describe the same resource with *a different metadata record*.
- use the same record identifier for a metadata record describing a
different resource


From CSW 2.0.2:





*4.8 identifier - a character string that may be composed of numbers and
characters that is exchanged between the client and the server with respect
to a specific identity of a resourceTable 1 — Common queryable
elementsIdentifier   a unique reference to the record within the catalogue*

*The mandatory GetRecordById request retrieves the default representation
of catalogue records using the record identifier.*



*A possible solution to the problem of duplicates of metadata entries
[...in federated catalogues...] is to define unique identifiers for
metadata entries that are applicable to a whole network, e.g. based on a
combination of the server URL and the file identifier specific to the
catalogue.Node-specific File identifiers alone are not the solution to the
problem, as different catalogues can use the same ID without referring to
the same dataset.*

I think that the "source of all evil" is that in the CSW and AP ISO specs,
a resource is identified:

- sometimes by the *fileIdentifier* of its metadata
- some other times by
*MD_Identification.citation.CI_Citation.identifier.MD_Identifier.code*.


The core queryables make it possible to query only on
MD_Metadata.fileIdentifier
The *GetRecordById* operation also works on *MD_Metadata.fileIdentifier*
(when we deal with ISO 19139 records and ISO AP 1.0 like we do in INSPIRE)

The *Additional queryable* properties are instead defined as follows:
ResourceIdentifier  identifier of the resource Identifier
MD_Metadata.identificationInfo.Abstract
*MD_Identification.citation.CI_Citation.identifier.MD_Identifier.code*
ParentIdentifier       *fileidentifier* of the metadata to which this
metadata is a subset (child) Identifier MD_Metadata.parentIdentifier

The support of Xpath expressions (e.g.
MD_DataIdentification/gmd:identifier/*/gmd:code
) as queryables  remains *optional* also in ISO AP 1.0.


Clearly, the possibility to use the fileIdentifier as Resource Identifier,
helps to overcome the limitations of the CSW specification.

In INSPIRE we must add to these difficulties the fact that the Unique
Resource Identifier must be able to support also a *namespace* in addition
to the code.




Some defiinions from ISO AP 1.0:






*Any identifier in a metadata set (most notably MD_Metadata.fileIdentifier
and MD_Metadata.parentIdentifier) shall comply with a UUID (Universal
Unique Identifier, as specified by http://www.ietf.org
<http://www.ietf.org>). The usage of UUIDs is recommended to ensure the
uniqueness of metadata sets across several catalogue
services.MD_Metadata.fileIdentifier: unique identifier for the given
metadata entity. This identifier is mandatory for this application
profile!9 The usage of a UUID (Universal Unique Identifier, as specified by
IETF (http://www.ietf.org <http://www.ietf.org>)) is recommended to ensure
identifier’s uniqueness.MD_Metadata.parentIdentifier: unique identifier for
a datasetcollection that is described elsewhere and which the metadata
entity belongs to. The usage of a UUID (Universal Unique Identifier, as
specified by IETF (http://www.ietf.org <http://www.ietf.org>)) is
recommended to ensure identifier’s uniqueness.*


Angelo

**Comment by michellutz** [comment]
[2017.4 meeting 2018-03-16] It is agreed that the ISO AP requirement does not make sense and that this should be discussed in section 2.2.1 of the MD TG v2.0 (in a corrigendum) along the lines taken in the U.S. Geoscience Information Network metadata document.

No change to ATS or ETS are required.

**Comment by michellutz** [comment]
@aquaglia @PeterParslow @ilkkarinne From your recent discussion in this thread, does anything speak against the conclusions from the meeting on 2018-03-16?

**Comment by PeterParslow** [comment]
I agree - we need a corrigendum to improve the MD TG, but the ATS / ETS have made the right interpretation, and need no change.

**Comment by aquaglia** [comment]
I agree that we need to explicitly state in the MD TG that we reject the AP
ISO requirement.
However, we should do that in a way that makes it clear for those who want
to enforce it, that they are allowed to do so.

**Comment by michellutz** [comment]
[2017.4 meeting 2018-04-19] The issue can be closed. The agreed TG corrigendum is tracked in https://ies-svn.jrc.ec.europa.eu/issues/3215
