### ISSUE TITLE
Modifications in ATS - Date and date type should be checked if the thesaurus is "GEMET - INSPIRE themes, version 1.0"

### ISSUE THREAD

**Issue by inakidiazdecerio** [inspire-eu-validation/metadata#132]
Date and title should be correct with respect to the given controlled vocabulary. For the "GEMET - INSPIRE themes, version 1.0"

**Comment by inakidiazdecerio** [comment]
A new branch has been created for helpdesk issues. Issue solved and changes have been pushed into helpdesk branch.

**Comment by michellutz** [comment]
[2017.4 meeting 2018-04-19] JRC to review the proposed change.
