### ISSUE TITLE
Modifications in TG - Date and date type should be checked if the thesaurus is "GEMET - INSPIRE themes, version 1.0"

### ISSUE THREAD

**Issue by inakidiazdecerio** [inspire-eu-validation/metadata#134]
Date and title should be correct with respect to the given controlled vocabulary. For the "GEMET - INSPIRE themes, version 1.0"

**Comment by michellutz** [comment]
We need to discuss where such TG-related issues should be created. Do we create a new repository for this??

**Comment by cportele** [comment]
@michellutz - So far the idea was to keep them here and tag them as "TG change recommended". I have added the tag here.

If there is a central issue tracker for the TGs (in Redmine?) then of course the issue should be closed here and added in that other issue tracker.

**Comment by michellutz** [comment]
ref #130

**Comment by michellutz** [comment]
[2017.4 meeting 2018-04-19] The issue can be closed. The agreed TG corrigendum is tracked on the MIG collaboration platform in https://ies-svn.jrc.ec.europa.eu/issues/3216
