### ISSUE TITLE
qualifying elements

### ISSUE THREAD

**Issue by mhogeweg** [inspire-eu-validation/metadata#141]
XML allows for qualifying elements using a default namespace declaration. 
```
<MD_Metadata xmlns="http://www.isotc211.org/2005/gmd" 
  ...
```

However, the INSPIRE validator appears to require the use of the gmd prefix.
```
<gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd" 
  ...
```

Is the use of the namespace prefix a requirement per INSPIRE guidlines?

**Comment by fabiovin** [comment]
Hi,
I tried to validate an xml file in which I removed the gmd prefix and it is valid.
What tests did you perform?
Fabio

**Comment by mhogeweg** [comment]
It may have been because the XML file does not include the specific XSD location.
