### ISSUE TITLE
GEMET API availability

### ISSUE THREAD

**Issue by mhogeweg** [inspire-eu-validation/metadata#168]
we are running into an issue frequently that the GEMET API are unavailable.

example:
https://www.eionet.europa.eu/gemet/getConceptsMatchingRegexByThesaurus?thesaurus_uri=http%3A%2F%2Fwww.eionet.europa.eu%2Fgemet%2Fconcept%2F&language=en&regex=water&jsonp=dojo_request_script_callbacks.dojo_request_script1

is this the right place to report such issues?

**Comment by fabiovin** [comment]
Dear @mhogeweg,

if you would like to report issues about the INSPIRE Reference Validator the repository is: https://github.com/INSPIRE-MIF/helpdesk-validator/issues.

For this specific issue, this isn't the right place.

I move this issue to the helpdesk-validator repository hoping that some user has had the same problem and has the solution!
