### ISSUE TITLE
Incorrect description of validation rule in quality of service README

### ISSUE THREAD

**Issue by arbakker** [inspire-eu-validation/metadata#177]
Description of validation rule in quality of service README is incorrect:

> Check that [Measurement Name](https://github.com/inspire-eu-validation/metadata/blob/2.0/sds-interoperable/quality-of-service.md#measurementName) element exists and it has an attribute xlink:href with URL value starting with "http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode/" and postfixed with one of values of code list QualityOfServiceCriteriaCode, see [Annex D.4 TG](https://github.com/inspire-eu-validation/metadata/blob/2.0/sds-interoperable/README.md#ref_TG_MD).

The url `http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode/` is not correct it should be `http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria/`, see https://github.com/inspire-eu-validation/ets-repository/blob/28b66265aab8fc8228672283887475818aade1ab/metadata/2.0/sds/ets-md-sdsinteroperable-bsxets.xml#L299

I assume that the situation in [ets-repository](https://github.com/inspire-eu-validation/ets-repository/blob/28b66265aab8fc8228672283887475818aade1ab/metadata/2.0/sds/ets-md-sdsinteroperable-bsxets.xml#L299) the correct implementation is.

**Comment by MarcoMinghini** [comment]
Dear @arbakker, please note that since approximately two years the Validator helpdesk was migrated to https://github.com/INSPIRE-MIF/helpdesk-validator/issues. I kindly invite to report issues there. Thank you.
