### ISSUE TITLE
Please ensure a maximum timeout is agreed upon that should be used when probing links

### ISSUE THREAD

**Issue by aquaglia** [inspire-eu-validation/metadata#9]

**Comment by aquaglia** [comment]
It is important to define a timeout in the ATS because at the abstract level I can ensure I do not fail a test by simply assuming the response take forever. Until the response is received I am unable to tell if it is wrong. Hence the test never fails.

**Comment by pvgenuchten** [comment]
@aquaglia, can we use the quality of service recommendations here:
view: 5sec
download: 30sec (for initial) 
discovery:  3sec
Or do you suggest to use more time, so those services with slower response will fail quality of service but besides that could be fine.

**Comment by jensscheerlinck** [comment]
Resolved by commit 01a52ee6fb99162e451e2e314a133f3248aac481
