### ISSUE TITLE
Open questions

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/metadata#92]
*This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685*
# Comment
The link to A.28.md.creation.date doesn't work and there's no chapter named like that.
# Proposed Change
Check and remove link or add A.28.md.creation.date to the ATS.

**Comment by pvgenuchten** [comment]
Where is this link mentioned?

**Comment by jensscheerlinck** [comment]
# Proposed Resolution

Remove A.28.md.creation.date from the "Open questions" sections of the Readme.md file.
It does not reference an existing test case.
