### ISSUE TITLE
Vocabulary

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/metadata#94]
*This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685*
# Comment
When an element is implemented as an Anchor as additional information not required by INSPIRE there is no need to check the validity of the link.
# Proposed Change
Remove this as a general test.

**Comment by jensscheerlinck** [comment]
# Proposed Resolution

The requirement that is checked is whether an element contains a valid (non-empty) characterString. 
Since an Anchor is considered as a valid, non-empty characterString, it should not be removed from this general test.

**Comment by aquaglia** [comment]
I think the comment refers to the following sentence:
"gmx:Anchor is typically used to reference a URI on which additional information is available. The validator could resolve the URI in the gmx:Anchor to validate if that content is available."

In particular to:
"The validator could resolve the URI in the gmx:Anchor to validate if that content is available."

**Comment by jensscheerlinck** [comment]
You are indeed correct @aquaglia 

Furthermore, the following open question is present at the bottom of the [Vocabulary ](https://github.com/inspire-eu-validation/ats-metadata#vocabulary) section:

Resolve: Goal is to check if a URL references an existing document. First the URL can be checked on syntactical correctness. Then a http head operation can give an indication of the availability of the document without fully downloading it. The operation might fail due to a number of reasons: the service is (temporarily) unavailable, the service is protected (status 403).

**Comment by aquaglia** [comment]
I would say that it makes more sense to check the URL (i.e. the value of the corresponding attribute of gmx:Anchor) only when that is an agreed URI which therefore carries an important semantic value.
And in that case the comparison can be even syntactical. The semantic value is not associated with what the URI returns, rather to the URI itself.
In all the other cases, it is a non-normative additional documentation about the text value of the anchor element, which is the only thing that is actually mandatory.
In those cases, and as a sort of nice to have, the URL can be opened and the content type checked and returned tor the user for further manual evaluation.

**Comment by jensscheerlinck** [comment]
Changed the resolution to rejected as the initial proposed resolution will not be carried out. Instead, the Readme.md and, specifically for this issue the concept of "resolving a URI", for the ATS will be rephrased as part of the ATS Restructuring in https://github.com/inspire-eu-validation/ats-cross-cutting/17
