### ISSUE TITLE
There are Open questions
There is no explicit Impl...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/metadata#98]
*This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685*
# Comment
There are Open questions
There is no explicit Implementation Requirement in TG MD for the following tests:
A.02.title
A.03.abstract
A.24.responsible.party.role
A.28.md.creation.date
Should these be excluded or included in the ATS? Or added as requirements in the TG MD?

**Comment by pvgenuchten** [comment]
As stated elsewhere, IMO some of these (title/creation-date) are required by iso19139. So as being conform to iso19139 is a requirement, there is no need to test them, so these requirements also needn't be in the TG. But in case other tests are suggested, which are not (yet) a requirement in TG, it would be good to (propose to) add them to TG, else remove the test.

**Comment by jensscheerlinck** [comment]
# Proposed Resolution

See proposed resolutions for issues #92 and #93

**Comment by pvgenuchten** [comment]
In miwp-5 meeting it was suggested that in the case of title/abstract inspire actually requires more then the xsd, besides being available, the fields should also have content.

**Comment by PeterParslow** [comment]
That is the proposed v2.0 Metadata TG, which is to be voted on at MIG & then phased in over three years. The general point is that we then have conformance classes which relate to versions of the TG - we're currently working on the current version.
(That's not to say I think that en empty title is good; just that it's currently allowed!)

**Comment by jensscheerlinck** [comment]
As discussed during the MIWP-5 meeting: a change request will be made to v1.3 of the TG MD. Furthermore ISO 19115 should be referenced.
Also, dependencies on base standards will be added as prerequisites to other test case.
